version: '3'
services:
  desktop:
    build: .
    container_name: xrdp
    restart: unless-stopped
    shm_size: 2g
    cap_add:
      - ipc_lock
    ports:
      - "127.0.0.1:3389:3389"
    volumes:
      - ./data/home/:/home/
      - ./data/opt/:/opt/
      - ./data/log/apt/:/var/log/apt/
      - ./data/log/journal/:/var/log/journal/
      - ./data/log/supervisor/:/var/log/supervisor/
      - ./data/tmp/:/tmp/
