version: '3'
services:
  desktop:
    build: .
    container_name: xrdp
    restart: unless-stopped
    shm_size: 2g
    cap_add:
      - ipc_lock
    ports:
      - "127.0.0.1:3389:3389"
    volumes:
      - /docker/xrdp/home/:/home/
      - /docker/xrdp/opt/:/opt/
      - /docker/xrdp/log/apt/:/var/log/apt/
      - /docker/xrdp/log/journal/:/var/log/journal/
      - /docker/xrdp/log/supervisor/:/var/log/supervisor/
